/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    MainPage: typeof import('./components/MainPage.vue')['default']
    MButton: typeof import('./components/m/button.vue')['default']
    MDATA_TABLE_README: typeof import('./components/m/DATA_TABLE_README.md')['default']
    MDATA_TABLE_USAGE: typeof import('./components/m/DATA_TABLE_USAGE.md')['default']
    MDataTable: typeof import('./components/m/data-table.vue')['default']
    MDataTableExample: typeof import('./components/m/data-table-example.vue')['default']
    MDropdownMenu: typeof import('./components/m/dropdown-menu.vue')['default']
    MInput: typeof import('./components/m/input.vue')['default']
    MSwitch: typeof import('./components/m/switch.vue')['default']
    MTablePagination: typeof import('./components/m/table-pagination.vue')['default']
    MToast: typeof import('./components/m/toast.vue')['default']
    MTOAST_USAGE: typeof import('./components/m/TOAST_USAGE.md')['default']
    MustExtractToComponent: typeof import('./components/must-extract-to-component.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    ProfileDropdown: typeof import('./components/ProfileDropdown.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheNavigation: typeof import('./components/TheNavigation.vue')['default']
    TheSidebar: typeof import('./components/TheSidebar.vue')['default']
    ToastContainer: typeof import('./components/ToastContainer.vue')['default']
  }
}
