/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddOrEditDialog: typeof import('./components/add-or-edit-dialog.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    MainPage: typeof import('./components/MainPage.vue')['default']
    MAutocomplete: typeof import('./components/m/autocomplete.vue')['default']
    MAutocompleteExample: typeof import('./components/m/autocomplete-example.vue')['default']
    MButton: typeof import('./components/m/button.vue')['default']
    MDataTable: typeof import('./components/m/data-table.vue')['default']
    MDialog: typeof import('./components/m/dialog.vue')['default']
    MInput: typeof import('./components/m/input.vue')['default']
    MREADMEAutocomplete: typeof import('./components/m/README-autocomplete.md')['default']
    MSwitch: typeof import('./components/m/switch.vue')['default']
    MTablePagination: typeof import('./components/m/table-pagination.vue')['default']
    MTextarea: typeof import('./components/m/textarea.vue')['default']
    MToast: typeof import('./components/m/toast.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    ProfileDropdown: typeof import('./components/ProfileDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    ToastContainer: typeof import('./components/ToastContainer.vue')['default']
  }
}
