/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/informations/categories': RouteRecordInfo<'/informations/categories', '/informations/categories', Record<never, never>, Record<never, never>>,
    '/informations/costTypes': RouteRecordInfo<'/informations/costTypes', '/informations/costTypes', Record<never, never>, Record<never, never>>,
    '/informations/dialogs/categories/add-or-edit-dialog': RouteRecordInfo<'/informations/dialogs/categories/add-or-edit-dialog', '/informations/dialogs/categories/add-or-edit-dialog', Record<never, never>, Record<never, never>>,
    '/informations/dialogs/costTypes/add-or-edit-dialog': RouteRecordInfo<'/informations/dialogs/costTypes/add-or-edit-dialog', '/informations/dialogs/costTypes/add-or-edit-dialog', Record<never, never>, Record<never, never>>,
    '/informations/dialogs/organizations/add-or-edit-dialog': RouteRecordInfo<'/informations/dialogs/organizations/add-or-edit-dialog', '/informations/dialogs/organizations/add-or-edit-dialog', Record<never, never>, Record<never, never>>,
    '/informations/dialogs/otherSources/add-or-edit-dialog': RouteRecordInfo<'/informations/dialogs/otherSources/add-or-edit-dialog', '/informations/dialogs/otherSources/add-or-edit-dialog', Record<never, never>, Record<never, never>>,
    '/informations/dialogs/paymentTypes/add-or-edit-dialog': RouteRecordInfo<'/informations/dialogs/paymentTypes/add-or-edit-dialog', '/informations/dialogs/paymentTypes/add-or-edit-dialog', Record<never, never>, Record<never, never>>,
    '/informations/dialogs/products/add-or-edit-dialog': RouteRecordInfo<'/informations/dialogs/products/add-or-edit-dialog', '/informations/dialogs/products/add-or-edit-dialog', Record<never, never>, Record<never, never>>,
    '/informations/dialogs/suppliers/add-or-edit-dialog': RouteRecordInfo<'/informations/dialogs/suppliers/add-or-edit-dialog', '/informations/dialogs/suppliers/add-or-edit-dialog', Record<never, never>, Record<never, never>>,
    '/informations/dialogs/warehouses/add-or-edit-dialog': RouteRecordInfo<'/informations/dialogs/warehouses/add-or-edit-dialog', '/informations/dialogs/warehouses/add-or-edit-dialog', Record<never, never>, Record<never, never>>,
    '/informations/organizations': RouteRecordInfo<'/informations/organizations', '/informations/organizations', Record<never, never>, Record<never, never>>,
    '/informations/otherSources': RouteRecordInfo<'/informations/otherSources', '/informations/otherSources', Record<never, never>, Record<never, never>>,
    '/informations/paymentTypes': RouteRecordInfo<'/informations/paymentTypes', '/informations/paymentTypes', Record<never, never>, Record<never, never>>,
    '/informations/products': RouteRecordInfo<'/informations/products', '/informations/products', Record<never, never>, Record<never, never>>,
    '/informations/suppliers': RouteRecordInfo<'/informations/suppliers', '/informations/suppliers', Record<never, never>, Record<never, never>>,
    '/informations/warehouses': RouteRecordInfo<'/informations/warehouses', '/informations/warehouses', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/operations/input_products_supplier': RouteRecordInfo<'/operations/input_products_supplier', '/operations/input_products_supplier', Record<never, never>, Record<never, never>>,
    '/operations/supplier-invoices/create': RouteRecordInfo<'/operations/supplier-invoices/create', '/operations/supplier-invoices/create', Record<never, never>, Record<never, never>>,
    '/operations/supplier-invoices/dialogs/pick-products': RouteRecordInfo<'/operations/supplier-invoices/dialogs/pick-products', '/operations/supplier-invoices/dialogs/pick-products', Record<never, never>, Record<never, never>>,
    '/operations/supplier-invoices/dialogs/selection-products': RouteRecordInfo<'/operations/supplier-invoices/dialogs/selection-products', '/operations/supplier-invoices/dialogs/selection-products', Record<never, never>, Record<never, never>>,
    '/operations/supplier-invoices/dialogs/selection-products-container': RouteRecordInfo<'/operations/supplier-invoices/dialogs/selection-products-container', '/operations/supplier-invoices/dialogs/selection-products-container', Record<never, never>, Record<never, never>>,
    '/operations/supplier-invoices/input': RouteRecordInfo<'/operations/supplier-invoices/input', '/operations/supplier-invoices/input', Record<never, never>, Record<never, never>>,
    '/operations/supplier-invoices/update/[id]': RouteRecordInfo<'/operations/supplier-invoices/update/[id]', '/operations/supplier-invoices/update/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
